---

- name:
  group: name="netadmins" gid="550" state=present
  tags: users

- name: create admin users
  user: name={{item.name}} state={{item.state}} comment={{item.comment}} uid={{item.uid}} password={{item.password}} group={{item.group}} groups={{item.groups}} shell="/bin/bash" generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=".ssh/id_rsa" update_password=on_create
  with_items: '{{admin_users}}'
  tags: users

